### PR TITLE
Committing Testcase2 in BranchX...

### PR DESCRIPTION
**Pull request by HariGitHub477**
Hi,

I have committed Testcase2. Please review and approve.

Regards,
NhpHari731

### CODE REVIEW

**Comment by NhpHari477** [comment]
Hi Hari731,

Can you add one more condition and commit the changes please.

Regards,
Hari477.

**Comment by HariGitHub477** [comment]
Hi Lead,

Updated testcase2, please review and approve it.

Regards,
Hari731

**Comment by NhpHari477** [comment]
Hi Hari731,

Code looks good, please go ahead and merge the code to Master Branch.

Regards,
Hari477

**Comment by HariGitHub477** [comment]
Hi Lead,

BranchX is merged to Master Branch.

Regards,
Hari731.

**Pull request merged**
